# Generated by Django 6.0.2 on 2026-03-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'Usage Report',
                'verbose_name_plural': 'Usage Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.analysisresult',),
        ),
    ]
